"""added food types and enum

Revision ID: 90871c26d13a
Revises: 43e8d21c62f4
Create Date: 2020-02-23 16:21:04.234892

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90871c26d13a'
down_revision = '43e8d21c62f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('food', sa.Column('food_type', sa.Enum('Vegetable', 'Fruit', 'Grain', 'Meat', 'Seafood', 'Dairy', 'Spice', name='foodtypes'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('food', 'food_type')
    # ### end Alembic commands ###
